name: flutter_listview
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

  font_awesome_flutter: ^10.2.1
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdfviewer: ^22.2.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - asset/proposal.pdf
